# Site settings
title: Advanced Computational Mechanics and Materials Laboratory
#email: niaz@rochester.com
description: > # this means to ignore newlines until "baseurl:"
   The Advanced Computational Mechanics and Materials Laboratory at the 
   University of Rochester, under principal investigator Niaz Abdolrahim.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acmml.com" # the base hostname & protocol for your site
#twitter_username: 
#github_username:  

# Build settings
markdown: kramdown

# Permalinks
#permalink: pretty
permalink: /news/posts/:month-:day-:year/:title/